votca/xtp

include/votca/xtp/aobasis.h, include/votca/xtp/aomatrix.h, include/votca/xtp/aoshell.h, include/votca/xtp/orbitals.h, include/votca/xtp/threecenters.h, netbeans/libxtp/nbproject/private/private.xml, src/libxtp/aomatrices/aocoulomb.cc, src/libxtp/aomatrices/aodipole.cc, src/libxtp/aomatrices/aodipole_potential.cc, src/libxtp/aomatrices/aoesp.cc, src/libxtp/aomatrices/aokinetic.cc, src/libxtp/aomatrices/aomatrix.cc, src/libxtp/aomatrices/aomomentum.cc, src/libxtp/aomatrices/aooverlap.cc, src/libxtp/aomatrices/aoquadrupole_potential.cc, src/libxtp/aoshell.cc, src/libxtp/dftengine/dftengine.cc, src/libxtp/fourcenter_rep.cc, src/libxtp/gwbse/bse_analysis.cc, src/libxtp/mixing.cc, src/libxtp/threecenter_rep.cc, src/libxtp/threecenters.cc, src/libxtp/threecenters_dft.cc
=> Fix warnings

netbeans/libxtp/nbproject/private/private.xml, src/libxtp/calculators/jobwriter.cc, src/libxtp/calculators/neighborlist.h, src/libxtp/gwbse/bse.cc, src/libxtp/gwbse/gwbse.cc, src/libxtp/numerical_integration/numerical_integrations.cc, src/libxtp/qmpackages/gaussian.cc
Small fix in bse.. please check!
Small fix in gwbse qpmax can now be largern than cmax
jobwriter has now more states options, 
neighborlist is more selective and faster
=> Extension of jobwriter and neighborlist to be more selective 

include/votca/xtp/elements.h
Fix #24 
Needed for votca/votca#13 and long term votca/votca#4
=> fix a clang-4 warning

include/votca/xtp/aomatrix.h, include/votca/xtp/gwbse.h, include/votca/xtp/threecenters.h, netbeans/libxtp/nbproject/private/private.xml, src/libxtp/aomatrices/aocoulomb.cc, src/libxtp/aomatrices/aooverlap.cc, src/libxtp/gwbse/gwbse.cc, src/libxtp/gwbse/rpa.cc, src/libxtp/jobcalculators/qmmm.h, src/libxtp/threecenters.cc
Removed the stabilisation routine from rpa because we do not understand it, it does not really influence the final result and it is faster without that routine.
=> Without rpa prepare

include/votca/xtp/aomatrix.h, src/libxtp/aomatrices/aocoulomb.cc, src/libxtp/aomatrices/aooverlap.cc, src/libxtp/gwbse/gwbse.cc, src/libxtp/gwbse/rpa.cc, src/libxtp/jobcalculators/qmmm.h, src/libxtp/threecenters.cc
Tested is svd inversion:
Not tested: higher threecenter overlaps and aooverlap above g
=> Matrix extension

.travis.yml
http://votca.github.io/doxygen/xtp-manual.pdf doesn't get updated anymore....
Broken in #28.
=> Fix manual location

.travis.yml, CMakeModules/gitscript.cmake, CMakeModules/gitversion.cmake
=> Switch CI to docker

src/libxtp/qmpackages/gaussian.cc
=> gaussian: fix compile with gcc-7

include/votca/xtp/elements.h
=> fixed elements.h Issue #72

include/votca/xtp/ERIs.h, include/votca/xtp/aobasis.h, include/votca/xtp/basisset.h, include/votca/xtp/bfgs-trm.h, include/votca/xtp/chargecarrier.h, include/votca/xtp/diis.h, include/votca/xtp/elements.h, include/votca/xtp/esp2multipole.h, include/votca/xtp/extractorfactory.h, include/votca/xtp/forces.h, include/votca/xtp/gdma.h, include/votca/xtp/geometry_optimization.h, include/votca/xtp/grid.h, include/votca/xtp/gyration.h, include/votca/xtp/jobcalculatorfactory.h, include/votca/xtp/lowdin.h, include/votca/xtp/nbo.h, include/votca/xtp/statesaversqlite.h, include/votca/xtp/threecenters.h, src/libxtp/aobasis.cc, src/libxtp/basisset.cc, src/libxtp/extractors/energyextractor.h, src/libxtp/extractors/integralsextractor.h, src/libxtp/extractors/occupationsextractor.h, src/libxtp/extractors/pairsextractor.h, src/libxtp/extractors/ratesextractor.h, src/libxtp/extractors/segmentsextractor.h, src/libxtp/extractors/trajextractor.h
Removed using namespace std; and namespace tools from xtp headers
=> removed using namespace .. form xtp header files

src/libxtp/calculators/kmcmultiple.cc, src/libxtp/calculators/kmcmultiple.h
Output of diffusion tensor every 1e9 steps
=> better kmcoutput every 1e9 steps

share/packages/orca_idft.xml, src/libxtp/jobcalculators/edft.h, src/libxtp/jobcalculators/idft.cc, src/libxtp/qmpackages/orca.cc
names for .gbw files are hardcoded so using it with the exciton calculator, which can use fragment guesses is harder.
=> orca used orca_mergefrac to build guess

share/doc/installation.dox
=>  doc: remove kmc (now in ctp)

include/votca/xtp/esp2multipole.h, include/votca/xtp/espfit.h, share/packages/esp2multipole.xml, src/libxtp/esp2multipole.cc, src/libxtp/espfit.cc, src/libxtp/orbitals.cc, src/tests/test_espfit.cc
Added pair and region constrains to espfit
=> Espfit constrain

.travis.yml
Once that works we should add the same block to all other VOTCA repos.
=> .travis.yml: only test some branches

src/libxtp/kmccalculator.cc
kmc nodes are only initialized once now.
=> Initial rates were initialized far too often

src/libxtp/orbitals.cc
The anti resonant contributions are wrong order.
I ll write a unit test soon
=> wrong contributions for AntiResonant contributions

src/libxtp/gwbse/bse.cc
outputs free interlevel dipoles if -v option is given for calculator
=> added interlevel output

include/votca/xtp/sigma.h, src/libxtp/gwbse/sigma.cc
Vectorized some code and reduced cache usage.
=> Small sigma opt

manual/fig/idft_flow/CMakeLists.txt, manual/reference/programs/CMakeLists.txt
=> Fix manual build

share/basis_sets/aux-cc-pVTZ.xml, share/basis_sets/cc-pVTZ.xml
converted from Basis Set Exchange
=> added cc-pVTZ and aux-cc-pVTZ to default share, for first 2 rows:

src/libxtp/gwbse/bse.cc
should fix the problems when qpmin is not zero
=> fixed mismatch between qpmin and vmin

src/libxtp/aobasis.cc, src/libxtp/aomatrices/aodipole.cc, src/libxtp/aomatrices/aoecp.cc, src/libxtp/aomatrices/aokinetic.cc, src/libxtp/aomatrices/aomatrix.cc, src/libxtp/aomatrices/aomomentum.cc, src/libxtp/aomatrices/aooverlap.cc, src/libxtp/aomatrices/aoplanewave.cc, src/libxtp/calculators/rates.h, src/libxtp/fourcenter.cc, src/libxtp/threecenter_dft.cc, src/libxtp/tools/gencube.h, src/libxtp/tools/spectrum.h
fixes https://github.com/votca/xtp/issues/220
=> removed exit calls

.gitlab-ci.yml
Related to https://github.com/votca/votca/issues/117
=> .gitlab-ci.yml: fix build from tags

.gitlab-ci.yml
Part of https://github.com/votca/votca/issues/114
=> .gitlab-ci.yml: add builddir as artifact

.gitlab-ci.yml
Part of https://github.com/votca/votca/pull/134
=> .gitlab-ci.yml: add rawhide and module builds

.codecov.yml, .travis.yml
Part of https://github.com/votca/votca/pull/132
=> Bring back coverage analysis

scripts/xtp_basisset.in, scripts/xtp_makeauxbasis.in, scripts/xtp_update_exciton.in
Part of https://github.com/votca/votca/issues/142
=> scripts/*.py: move to python3

src/libxtp/gwbse/bse_operator.cc
@NicoRenaud maybe this helps speed up the bse a bit. It should allocate a lot less memory.
=> Increase H_x speed. This is not tested yet

include/votca/xtp/votca_config.h.in, src/tests/test_espfit.cc
reduced size of the espfit unit test should fix https://github.com/votca/xtp/issues/229
=> shortened unit test

include/votca/xtp/bse_operator.h, include/votca/xtp/davidsonsolver.h, include/votca/xtp/matrixfreeoperator.h, src/libxtp/gwbse/bse.cc, src/libxtp/gwbse/bse_operator.cc, src/tests/test_bse_operator.cc
should completely eliminate race condition and maybe even improve performance
=> rewrote caching to not have to use critical sections anymore

manual/CMakeModules/FindINKSCAPE.cmake
Fix https://github.com/votca/votca/issues/180
=> cmake: fix inkscape detection for beta versions

include/votca/xtp/bse_operator.h, src/libxtp/aomatrices/aomatrix.cc, src/libxtp/aomatrices/aopotential.cc, src/libxtp/dftengine/ERIs.cc, src/libxtp/eeinteractor.cc, src/libxtp/gwbse/bse_operator.cc
=> Removed triangular view

include/votca/xtp/matrixfreeoperator.h
matrixfreeoperator inherited from the wrong type, I have no idea why it worked.
=> corrected wrong inheritance in matrixfreeoperator

src/libxtp/davidsonsolver.cc
One line that changes a lot the performance
=> Compute only the thin Q in the QR decompsition

include/votca/xtp/bseoperator_btda.h, src/tests/test_davidson.cc
If you approve can you run the benchmark again?
=> btda_operator is now a lot faster

include/votca/xtp/davidsonsolver.h, src/libxtp/davidsonsolver.cc, src/libxtp/gwbse/bse.cc, src/tests/test_bse.cc, src/tests/test_davidson.cc
Merge after https://github.com/votca/xtp/pull/315
=> Davidson pp

include/votca/xtp/checkpoint_utils.h
for https://github.com/votca/votca/issues/228
=> suppress icc warning

include/votca/xtp/checkpointreader.h, src/libxtp/dftcoupling.cc
fixes  https://github.com/votca/xtp/issues/338
=> do not read empty vectors

CHANGELOG.md, include/votca/xtp/huffmantree.h
=> fix gcc10 warnings

CHANGELOG.md, src/libxtp/grids/vxc_grid.cc
=> fix build on 32-bit

CHANGELOG.md, include/votca/xtp/bse.h, include/votca/xtp/gw.h, include/votca/xtp/orbitals.h, src/libxtp/bsecoupling.cc, src/libxtp/gwbse/bse.cc, src/libxtp/gwbse/gwbse.cc, src/libxtp/orbitals.cc, src/tests/test_bse.cc, src/tests/test_bsecoupling.cc
rpa energies are now saved.
This change is not backward compatible
=> G0w0 rpa fix

CHANGELOG.md, include/votca/xtp/dipoledipoleinteraction.h, include/votca/xtp/logger.h, include/votca/xtp/matrixfreeoperator.h, src/libxtp/progressobserver.cc, src/libxtp/qmpackages/gaussian.cc, src/libxtp/statetracker.cc, src/libxtp/tools/apdft.h
Related to https://github.com/votca/tools/issues/216
=> fix clang 10 warnings

CHANGELOG.md, include/votca/xtp/bse.h, src/libxtp/gwbse/gwbse.cc
=> Use of off-diagonal elements of Hqp in BSE optional

CHANGELOG.md, include/votca/xtp/settings.h, src/libxtp/settings.cc
=> check executable for dft jobs other than xtp

include/votca/xtp/polarregion.h, share/xtp/xml/molpol.xml, src/libxtp/polarregion.cc, src/libxtp/tools/molpol.cc, src/libxtp/tools/molpol.h, src/tests/test_eigen.cc
Molpol now will also work for single atoms and return the correct polarisation. 
Refactored polarregion a bit and added preconditioner.
=> hopefully fixed molpol added a pcg test for eigen

include/votca/xtp/qmpackage.h, share/xtp/xml/dftgwbse.xml, src/libxtp/gwbse/gwbseengine.cc, src/libxtp/qmpackages/xtpdft.cc
=> removed mo and log file options from gwbse engine

include/votca/xtp/xtpapplication.h, share/packages/qmpackage_defaults.xml, share/xtp/xml/dftgwbse.xml, src/libxtp/gwbse/gwbseengine.cc, src/libxtp/tools/dftgwbse.cc, src/libxtp/tools/dftgwbse.h, src/libxtp/xtpapplication.cc, src/tools/xtp_parallel.cc, src/tools/xtp_run.cc, src/tools/xtp_tools.cc
See: #319 
* Make the `-o` (**options file**) command line option optional
=> Felipe defaults xml

CHANGELOG.md, include/votca/xtp/dipoledipoleinteraction.h, src/tests/test_eeinteractor.cc
Fix https://github.com/votca/xtp/issues/341
=> cast to scalar and changed polar distance

CHANGELOG.md, CMakeLists.txt
Fix #436 
Hackish alternative to #437
=> cmake: inject -Wno-deprecated-copy for hdf5-1.10.4

CHANGELOG.md, src/libxtp/jobcalculators/iqm.cc
=> fixed path

.github/workflows/forward-to-votca.yml, CHANGELOG.md
This action will forward commit to master to `votca/votca` automaticallly when finished.
=> GH Action: add forward action

CHANGELOG.md, share/doc/qmpackages.rst, src/libxtp/qmpackage.cc, src/libxtp/qmpackages/orca.cc
=> Hotfix votcashare path

CHANGELOG.rst, src/libxtp/qmpackages/orca.cc, src/libxtp/qmpackages/orca.h, src/libxtp/settings.cc, src/tests/test_settings.cc
Fix #504 by properly *pointcharges* in the Orca input.
=> Properly write point charges in Orca

CHANGELOG.rst, src/libxtp/jobcalculators/eqm.cc
@baumeier can you check if this fixes https://github.com/votca/xtp/issues/507
=> added more checks to the dft_parse_part

CHANGELOG.rst, src/libxtp/qmpackages/orca.cc, src/tests/test_orca.cc
=> fixing double SCF in orca input line

CHANGELOG.rst, include/votca/xtp/eigen.h
=> a possible clang fix

CHANGELOG.rst, include/votca/xtp/gw.h, src/libxtp/gwbse/gw.cc
=> Sigma derivative fix

CHANGELOG.md, src/libxtp/qmpackages/gaussian.cc
=> fixing the Gaussian keyword for guess reading

src/libxtp/basisset.cc, src/libxtp/ecpbasisset.cc, src/libxtp/qmpackage.cc, src/libxtp/qmpackages/orca.cc
using https://github.com/votca/tools/pull/302
=> Getenv votcashare

CHANGELOG.rst, include/votca/xtp/kmccalculator.h, src/libxtp/calculators/kmclifetime.cc, src/libxtp/calculators/kmcmultiple.cc, src/libxtp/kmccalculator.cc
=> updated logger and made it cout

CHANGELOG.rst, include/votca/xtp/molden.h, include/votca/xtp/orbreorder.h, src/libxtp/qmpackages/orca.h, src/libxtp/qmpackages/xtpdft.h
Report on mailing list: https://groups.google.com/g/votca/c/l-5RSrxQegk/m/X1OcT_0gAwAJ
=> fix build on older gcc

CHANGELOG.rst, src/libxtp/qmregion.cc
=> Correct total energy in QMMM with QP

CHANGELOG.rst, src/libxtp/qmregion.cc
=> Removed unnecessary index shift

CHANGELOG.md, include/votca/xtp/logger.h
probably fixes #623, we have had the error before on `master` and this commit fixed it then.
=> fix log error on stable

CHANGELOG.rst, share/xtp/xml/densityanalysis.xml, src/libxtp/tools/densityanalysis.h
=> Densityanalysis fix

CHANGELOG.rst
=> CHANGELOG.rst: update

CHANGELOG.rst, include/votca/xtp/aobasis.h, include/votca/xtp/aoshell.h, include/votca/xtp/atom.h, include/votca/xtp/atomcontainer.h, include/votca/xtp/checkpointreader.h, include/votca/xtp/checkpointtable.h, include/votca/xtp/checkpointwriter.h, include/votca/xtp/ecpaobasis.h, include/votca/xtp/ecpaoshell.h, include/votca/xtp/polarsite.h, include/votca/xtp/qmatom.h, include/votca/xtp/qmpair.h, include/votca/xtp/qmstate.h, include/votca/xtp/staticsite.h, src/libxtp/aobasis.cc, src/libxtp/aoshell.cc, src/libxtp/atom.cc, src/libxtp/ecpaobasis.cc, src/libxtp/ecpaoshell.cc, src/libxtp/polarsite.cc, src/libxtp/qmatom.cc, src/libxtp/qmnblist.cc, src/libxtp/qmpair.cc, src/libxtp/staticsite.cc
Now the `setupCptTable` is a static method of each class, which separates layout and writing data better. 
@pmadhikar just if you are curious still.
=> refactored tables to not have to use dummy elements anymore

include/votca/xtp/rpa.h, src/libxtp/gwbse/rpa.cc
=> refactoring energy corrections outside qpmin:qpmax for RPA

CHANGELOG.rst, include/votca/xtp/orbitals.h
=> BSE triplets with dynamical screening stored

CHANGELOG.rst, scripts/xtp_autogen_mapping.in, scripts/xtp_basisset.in, scripts/xtp_makeauxbasis.in, scripts/xtp_qmmm2qm.in, scripts/xtp_update_mapfile.in
* fix #656
* Add Votca headers to the scripts
=> add headers to scripts #656

CHANGELOG.rst, scripts/xtp_autogen_mapping.in
=> Properly the count the number of available CPU for autogen_mapping script

CHANGELOG.rst, src/libxtp/qmpackages/orca.cc, src/tests/test_orca.cc
=> Problem with path of executable for orca_2mkl + problem reading the Molden file.

CHANGELOG.rst, scripts/xtp_autogen_mapping.in
A fragment can have only one atom. This should fix the problem.
=> Fix the fact that a fragment can be made of one atom only

CHANGELOG.rst, include/votca/xtp/jobtopology.h, include/votca/xtp/qmfragment.h, src/libxtp/jobcalculators/qmmm.cc, src/libxtp/jobtopology.cc
jobtopology can read hdf5 files now. 
Some small changes using more std::algorithm and some other small refactors.
=> HDF5 qmmm checkpoint reader

CHANGELOG.rst, include/votca/xtp/bse.h, share/xtp/xml/neighborlist.xml, src/libxtp/calculators/neighborlist.cc, src/libxtp/gwbse/gwbse.cc, src/libxtp/jobcalculators/eqm.cc, src/tests/test_bse.cc
https://groups.google.com/g/votca/c/4bgodqD7vxs
=> fixed bugs to make tutorial work again

CHANGELOG.rst, include/votca/xtp/segmentmapper.h, src/libxtp/gwbse/gwbse.cc, src/libxtp/jobcalculators/iqm.cc, src/libxtp/jobcalculators/iqm.h, src/libxtp/jobcalculators/qmmm.cc, src/libxtp/qmstate.cc, src/libxtp/segmentmapper.cc
A collection of small refactors, most major is to rework the complicated jobfile reading from iqm.
=> Minor refactor

CHANGELOG.rst, src/tools/xtp_parallel.cc
=> renamed some

src/libxtp/polarregion.cc, src/libxtp/tools/log2mps.h, src/libxtp/tools/molpol.cc
I will collect all minor things that might need changing with suggested changes in this PR.
=> fixes to options refactor

share/xtp/xml/qmmm.xml, src/libxtp/jobcalculators/qmmm.cc, src/libxtp/jobcalculators/qmmm.h
These are the same extra options as in the previous PR but now based on the `options_refactor` branch.
=> add qmmm options

CHANGELOG.rst, src/libxtp/bsecoupling.cc
fix https://github.com/votca/xtp/issues/447
=> fixed bsecoupling checks

CHANGELOG.rst, src/libxtp/numerical_integration/vxc_potential.cc
=> improved vxc performance by 20%

include/votca/xtp/atomcontainer.h, include/votca/xtp/mmregion.h, include/votca/xtp/parallelxjobcalc.h, include/votca/xtp/progressobserver.h, include/votca/xtp/qmpackage.h, include/votca/xtp/segmentmapper.h, src/libxtp/qmpackages/orca.cc
=> added clearer types
