- src/libxtp/aobasis.cc
start order defaulted to gaussian/nwchem and ignored possibility of votca order (legacy)
> AOBasis: fixed shell reordering

- src/libxtp/calculators/kmcmultiple.cc
- everything is in nm, except the electric field (`_field`) which is given in V/m. Added factor 10E-9 to fix.
- `nexttrajoutput` was initialized with `_runtime`, but should start at 0 (or maybe at `outputtime/step`).
- When outputtime was put to 0, `step%outputstep` in l.268 would throw a Floating Point exception. `checkifoutput` is only checked after that. Switched it around.
- When `runtime` is in steps (>100), l.268 assumed that `outputtime` ist also in steps. If `outputtime` was given in seconds < 1, it would initialize `outputsteps` as 0 and again throw a Floating Point exception. Added checks to give the user better error/warning messages.
- `tfile` was opened even when `checkifoutput==false`. Put it in the appropriate place.
I looked into changing the cout's to the logger. Couldn't …
> fix outputtime issues, floating point exception, unit error

- src/libxtp/aobasis.cc
Bug fix for lack of multiplication when reordering matrices.
Implementation by Jens. I just discovered and localized the bug.
> AOBasis: multiply AO matrix elements when reordering it too.

- CMakeLists.txt
Details see: https://svn.boost.org/trac10/ticket/10038
Fix #106
> cmake: bump boost to avoid copy_file() + C++11 bug

- src/tools/Md2QmEngine.cc
Just skip the second which does not contain any useful information.
Fix #141
> correction xyzreader

- include/votca/xtp/aobasis.h
- include/votca/xtp/aomatrix.h
- include/votca/xtp/dftengine.h
- include/votca/xtp/esp2multipole.h
- include/votca/xtp/orbitals.h
- netbeans/libxtp/nbproject/configurations.xml
- share/xtp/xml/kmcmultiple.xml
- src/libxtp/aobasis.cc
- src/libxtp/aomatrices/aodipole.cc
- src/libxtp/aomatrices/aomatrix.cc
- src/libxtp/dftengine/dftengine.cc
- src/libxtp/esp2multipole.cc
- src/libxtp/gwbse/bse.cc
- src/libxtp/gwbse/gwbse.cc
- src/libxtp/orbitals.cc
- src/tests/test_bse.cc
- src/tests/test_hdf5.cc
- src/tests/test_orbitals.cc
- closing issue https://github.com/votca/xtp/issues/156
- made BSE errors more explicit
- made AOMatrix::FillBlock a pure virtual function, e.g it has to be implemented by derived class
- converted some member variables to lower case
- aodipole now has a method to set the center around which the dipole can be calculated, defaults to origin
-fixed bug in bse fragment analysis, before it was always executed.
> Output of dipoles for states

- include/votca/xtp/checkpointreader.h
- include/votca/xtp/checkpointwriter.h
- src/libxtp/orbitals.cc
Now we simply cast before and after the read. Just as before the
callers define the type, so it works the same as before but with a
specialized functions dealing with bools.
Fix #159
> Fix reading and writing bool to hdf5 by casting to/from int

- src/libxtp/bsecoupling.cc
- src/libxtp/dftengine/dftengine.cc
- src/libxtp/gyration.cc
- src/libxtp/jobcalculators/iexcitoncl.cc
- src/libxtp/orbitals.cc
- src/libxtp/polarsegment.cc
- src/libxtp/qmmolecule.cc
- src/tests/test_fragment.cc
Any source files that were missing the using namespace std; line were addressed so that when the header files in tools are fixed it does not create problems for xtp.
> Clean namespace from using

- include/votca/xtp/gw.h
- include/votca/xtp/gwbse.h
- include/votca/xtp/rpa.h
- include/votca/xtp/sigma_base.h
- include/votca/xtp/sigma_ppm.h
- src/libxtp/gwbse/bse.cc
- src/libxtp/gwbse/gw.cc
- src/libxtp/gwbse/rpa.cc
- src/libxtp/gwbse/sigma_ppm.cc
- src/tests/test_ppm.cc
- src/tests/test_rpa.cc
- src/tests/test_sigma_ppm.cc
- made the interface of the sigma base class more open
- sigma now has access to a `const RPA` object during its whole lifetime
- `GW` has an `RPA `member 
-` RPA` owns the energies it needs to evaluate the RPA
> changed sigma interface

- src/libxtp/gwbse/gwbse.cc
ignore_corelevels is no longer just true and false:
if you specify `BSE`only core levels in BSE calculation will be ignored
if you specify `GW`only core levels in GW and BSE calculation will be ignored
if you specify `RPA`only core levels in RPA, GW and BSE calculation will be ignored
> added ignore corelevel options

- include/votca/xtp/molecule.h
- src/libxtp/molecule.cc
- src/libxtp/tools/pdb2map.h
- src/tests/test_molecule.cc
the xtp molecule is a wrapper for the csg basemolecule. Currently, the xtp molecule is not using the structural methods associated with csg base molecule but that will change. Should be built against csg::joshs-development branch to work.
> Private inheritance of csg basemolecule to xtp molecule

- src/tools/CMakeLists.txt
Doing this will allow us to separate the different tests e.g.
ctest -R unit
ctest -R integration
ctest -R memory
> Prepended integration to integration tests

- CHANGELOG.md
- scripts/xtp_basisset.in
- scripts/xtp_makeauxbasis.in
- scripts/xtp_update_exciton.in
Fix for stable on newer fedora versions.
Part of https://github.com/votca/votca/pull/222
> scripts: use python3 for scripts

- share/packages/xtpdft.xml
- src/libxtp/jobcalculators/iqm.cc
While using votca I encountered two "problems". 
The first, in the `iqm.cc` file, a log file for the dft calculation is only created if the dft calculation is successful. On failure, however, no `dft.log` is printed. I simply added a line of code that prints a `dft.log` on failure.
The second, in the `xtpdft.xml` file, `max_iterations` was placed in the `package` element, but the code tries to read it from the `package/convergence` element. I simply moved it so the code can read it. (for how the option is read see: `dftengine.cc` line 114)
> xml and logger update

- CHANGELOG.md
- include/votca/xtp/bse.h
- src/libxtp/gwbse/bse.cc
- src/libxtp/gwbse/gwbse.cc
- src/tests/test_bse.cc
Implements #402 better than #403: 
- moved to BSE object and into configure function
- changed default to using offdiagonals for backwards consistency
- addition to BSE unit test
> Better option for Hqp offdiagonals in BSE 

- CHANGELOG.md
- include/votca/xtp/aobasis.h
- include/votca/xtp/basisset.h
- include/votca/xtp/qmpackage.h
- src/libxtp/aobasis.cc
- src/libxtp/basisset.cc
- src/libxtp/qmpackage.cc
- src/libxtp/qmpackages/orca.h
- src/libxtp/qmpackages/xtpdft.h
- src/tests/test_basisset.cc
- Removed all the recursion in basisset.cc and replaced it with for loops for better readability and added some tests
- Moved ReorderMOs from AOBasis to QMPackage
- Input format of types is now checked
- The Reorder parameters are now stored in the qmpackage and not hardcoded in aobasis.cc
> Refactor of aobasis

- include/votca/xtp/parallelxjobcalc.h
- share/xtp/xml/eqm.xml
- share/xtp/xml/iexcitoncl.xml
- share/xtp/xml/iqm.xml
- share/xtp/xml/qmmm.xml
- src/libxtp/jobcalculators/eqm.cc
- src/libxtp/jobcalculators/eqm.h
- src/libxtp/jobcalculators/iexcitoncl.cc
- src/libxtp/jobcalculators/iexcitoncl.h
- src/libxtp/jobcalculators/iqm.cc
- src/libxtp/jobcalculators/iqm.h
- src/libxtp/jobcalculators/qmmm.cc
- src/libxtp/jobcalculators/qmmm.h
- src/libxtp/parallelxjobcalc.cc
See: #319
* For the `xtp_parallel` calculator the options file is no longer mandatory.
* Changed signature for `ParallelXJobCalc<JobContainer>::ParseCommonOptions` method
**Calculators**:
> allow options file to be optional for xtp_parallel

- CHANGELOG.md
- include/votca/xtp/bsecoupling.h
- share/xtp/xml/eqm.xml
- share/xtp/xml/iqm.xml
- src/libxtp/bsecoupling.cc
Remove the default values from the header file of `bsecoupling`  into the Calculator XML files (e.g. `iqm`)
> mv bsecoupling defaults to the xml files

- CHANGELOG.md
- include/votca/xtp/checkpoint.h
- src/libxtp/calculators/kmclifetime.cc
This is to fix the problem of inheriting includes from tools, https://github.com/votca/tools/pull/246.
Addressed deepcode warnings.
> Addressed missing includes

- CHANGELOG.md
- CMakeLists.txt
- include/votca/xtp/dipoledipoleinteraction.h
- include/votca/xtp/eigen.h
- include/votca/xtp/matrixfreeoperator.h
- include/votca/xtp/orbitals.h
- include/votca/xtp/qmtool.h
- src/libxtp/CMakeLists.txt
- src/libxtp/dftengine/ERIs.cc
- src/libxtp/gwbse/rpa.cc
- src/libxtp/numerical_integration/density_integration.cc
- src/libxtp/numerical_integration/vxc_potential.cc
- src/tests/test_aopotential.cc
- src/tests/test_bse_operator.cc
- src/tests/test_threecenter_dft.cc
Openmp is now required in version 4.5
this is not a big problem for gcc and icc but clang is a bit stupid, so you have to have clang-10 to use it properly. This seems to be a bug in the clang package.
> using reductions instead of handcrafted resolutions

- .github/workflows/continuous-integration-workflow.yml
- CHANGELOG.md
- CMakeLists.txt
Fixing https://github.com/votca/xtp/issues/469
> openmp is deactivated for clang<10

- CHANGELOG.md
- share/xtp/xml/dftgwbse.xml
- share/xtp/xml/iqm.xml
XML use hexadecimals to represent some unicode symbols like `-` that is represented as `&#x2013;`.
These symbols are causing some translation problem when transforming the XML files into RST.
Remove the special symbols.
> remove special xml symbols

- .github/workflows/coverage.yml
- CHANGELOG.rst
https://github.com/votca/xtp/pull/500#issuecomment-654583279
> CI: turn coverage into own action

- CHANGELOG.rst
- src/libxtp/gwbse/gw.cc
implements https://github.com/votca/xtp/issues/492
due to the parallelization, it is not guaranteed that the output is ordered by level index, but the index->qp_weight,qp_energy is always correctly output.
> added qp root output

- .github/workflows/create-release.yml
- CHANGELOG.md
Same as #518, but we seem to need this on `stable` as well for the `v1.6.2` release.
> GHA: create release workflow on stable

- CHANGELOG.rst
- include/votca/xtp/jobtopology.h
- include/votca/xtp/orbitals.h
- include/votca/xtp/topology.h
- src/libxtp/jobtopology.cc
- src/libxtp/orbitals.cc
- src/libxtp/statesaver.cc
- src/libxtp/topology.cc
Introduced version numbers for qmmm checkpoint, orbital files and topology files. 
This allows to later introduce backwards compatible changes. 
uses `int` because they can be equality compared.
> added versions to files and made the lock for stateserver better

- CHANGELOG.rst
- src/libxtp/statesaver.cc
I changed the locking behaviour earlier to make them more robust, but I forgot the case if no state file exists yet.
> fix case no statefile exists yet and improved warnings

- CHANGELOG.rst
- include/votca/xtp/settings.h
- share/xtp/data/qmpackage_defaults.xml
- share/xtp/xml/dftgwbse.xml
- share/xtp/xml/eanalyze.xml
- share/xtp/xml/eqm.xml
- share/xtp/xml/ianalyze.xml
- share/xtp/xml/iexcitoncl.xml
- share/xtp/xml/iqm.xml
- share/xtp/xml/molpol.xml
- share/xtp/xml/neighborlist.xml
- src/libxtp/calculators/eanalyze.cc
- src/libxtp/calculators/ianalyze.cc
- src/libxtp/calculators/neighborlist.cc
- src/libxtp/dftengine/dftengine.cc
- src/libxtp/gwbse/gwbse.cc
- src/libxtp/jobcalculators/iexcitoncl.cc
- src/libxtp/tools/dftgwbse.cc
- src/libxtp/tools/molpol.cc
- src/tests/test_dftengine.cc
see issue #508 
Remove the `constant` keyword from the defaults of the `neighborlist` calculator.
> remove constant from neighborlist defaults

- CHANGELOG.rst
- src/libxtp/qmpackages/orca.cc
- src/libxtp/qmpackages/orca.h
- src/tests/test_orca.cc
see #552 
Check whether the Orca keyword is single or multi-line and print it accordingly
> fix single/multiline keywords in Orca

- CHANGELOG.rst
- src/tests/test_orca.cc
Unit test was there, but no check was done for the polar part
> perform check in orca unit test 

- CHANGELOG.rst
- include/votca/xtp/atomcontainer.h
- include/votca/xtp/qmmolecule.h
- src/libxtp/gwbse/gwbse.cc
fixes #597 
Or at least so I think, there are two assumptions:
- That it is fine to make a copy of the incoming atoms
- That the ID's of incoming molecules always start from zero
@JensWehner are these valid assumptions?
> AddContainer updates ID

- CHANGELOG.rst
- src/libxtp/qmpackages/orca.cc
Orca coordinate writer has now higher precision, like the default .xyz files
> orca coordinate precision

- CHANGELOG.rst
- src/libxtp/md2qmengine.cc
- src/tools/xtp_map.cc
This is connected to https://github.com/votca/csg/pull/657
> Switch to unique ptr for molecules stored in csg topology class. 

- CHANGELOG.rst
- include/votca/xtp/settings.h
- share/xtp/data/qmpackage_defaults.xml
- share/xtp/xml/dftgwbse.xml
- src/libxtp/dftengine/dftengine.cc
- src/libxtp/qmpackages/orca.cc
- src/tests/test_dftengine.cc
I am trying to make the numerical polarizability calculator part of PyVotca. But I ran into problems with the options, setting an external field was very hard, because it is hidden now in the `qmpackage_defaults.xml`. What I did here is two things
1. I made the external field options part of the general package (within `dftgwbse.xml`) instead of only the xtp package
2. I added the option to print the external field to the orca input file, so one can also do calculations with an external field using orca.
My main concern with this pull request is that I understand the options handling to poorly and that there is possibly a better way of achieving the same thing. So have a critical look and let me know what you think.
> Add option for ext. field to xtp and orca

- CHANGELOG.rst
- include/votca/xtp/symmetric_matrix.h
- src/libxtp/threecenter.cc
For large systems it speeds the allocation up, the hope is also that the matrices are better distributed in 2-socket architectures
> matrices are allocated in parallel

- CHANGELOG.rst
- include/votca/xtp/cudamatrix.h
- include/votca/xtp/cudapipeline.h
- include/votca/xtp/openmp_cuda.h
- src/libxtp/openmp_cuda.cc
- src/libxtp/xtpapplication.cc
add command line option for gpus to xtp.
The implementation is not perfect, basically I use sort of a global variable, but in some sense OPENMP does the same, so maybe it is okay at least for now.
> add command line option

- CHANGELOG.rst
- src/libxtp/stateapplication.cc
- src/libxtp/tools/dftgwbse.cc
- src/libxtp/xtpapplication.cc
- src/tools/xtp_tools.cc
@baumeier  please acknowledge
This PR removes the `-n` option from tools instead it adds the `-c` options which allows you to change xml options from the commandline via `a.b=value` mutliple options can be changed by separating them with whitespaces.
> reworked commandline access

- CHANGELOG.rst
- include/votca/xtp/aoshell.h
- include/votca/xtp/cudamatrix.h
- include/votca/xtp/gridbox.h
- src/libxtp/aoshell.cc
- src/libxtp/bsecoupling.cc
- src/libxtp/davidsonsolver.cc
- src/libxtp/dftcoupling.cc
- src/libxtp/dftengine/dftengine.cc
- src/libxtp/grids/gridbox.cc
- src/libxtp/gwbse/bse_operator.cc
- src/libxtp/gwbse/gwbse.cc
- src/libxtp/gwbse/rpa.cc
- src/libxtp/numerical_integration/amplitude_integration.cc
- src/libxtp/numerical_integration/density_integration.cc
- src/libxtp/numerical_integration/vxc_potential.cc
- src/libxtp/openmp_cuda.cc
- src/libxtp/orbitals.cc
- src/libxtp/self_energy_evaluators/sigma_exact.cc
- src/libxtp/self_energy_evaluators/sigma_exact.h
- src/libxtp/statefilters/Overlap_filter.cc
- src/libxtp/threecenter.cc
- src/tests/test_aoshell.cc
This PR does two things: 
a) use `middleCols` `middleRows` instead of `block` 
b) Refactor the Handling of AOValues evaluated at gridPoints to be more functional
> using eigen middleCol and middleRow functions

- share/xtp/xml/subpackages/gwbse.xml
Gianluca found a typo in one of the default files. This is the fix.
> Fixed Typo in gwbse.xml
